### ISSUE TITLE
RMT RAM  definition

### ISSUE THREAD

**Issue by Gustavomurta** [DavidAntliff/esp32-utils#1]
Good news, David . 
See chapter **15.2.2 RMT RAM** at **ESP32 Technical Reference Manual Version 2.9**
https://www.espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf

" The data structure in RAM is shown in Figure 89. Each 32-bit value contains two 16-bit entries, with two fields in every entry, ”level” and ”period”. ”Level” indicates whether a high-/low-level value was received or is going to be sent, while ”period” points out the divider-clock cycles for which the level lasts. A zero period is interpreted as an end-marker: the transmitter will stop transmitting once it has read this, and the receiver will write this, once it has detected that the signal it received has gone idle."

**Comment by DavidAntliff** [comment]
Yes, this is what the RMT version of the DCO code uses. It calculates the longest complete cycle it can fit into the RAM to get the best accuracy. However the algorithm I use could do with some review/rework so if you see a better way to do it, please let me know.

**Comment by DavidAntliff** [comment]
Did you mean to file this under this project, or the DCO one at https://github.com/DavidAntliff/esp32-dco?

**Comment by Gustavomurta** [comment]
Yes, as I read at https://github.com/DavidAntliff/esp32-dco. But by studying the code, I realize that it is already up to date.

**Comment by DavidAntliff** [comment]
No problem :)
